name: "My action"
desciption: "Test my action"

inputs:
  message:
    description: "The message to print"
    required: true
    default: "Hola" # Valor por defecto

runs:
  using: "composite" # acciones de tipo composite permiten agrupar pasos comunes

  steps:
    - name: Hola Mundo
      run: echo "Hola ${{ inputs.message }}"
      shell: bash