name: Test

on:
  push:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: ls
        run: ./.github/actions/my-action
        shell: bash