name: Variables y Secretos

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      MY_VAR: SIUU

    steps:
      - name: Test
        env:
          STEP_MY_VAR: GOAT
        run: echo "EL $STEP_MY_VAR ${{ MY_VAR }}!!!"