name: Test5

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: true
        default: 'test'

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: ls
        run: ls -al